name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  benchmark:
    strategy:
      matrix:
        benchmark:
          - simple
          - nested
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - uses: raviqqe/enable-homebrew@main
      - run: brew install ninja
      - run: cargo install --path . --locked
      - run: benchmark/${{ matrix.benchmark }}/main.sh
  benchmark_test:
    runs-on: ubuntu-latest
    needs: benchmark
    if: always()
    steps:
      - run: test ${{ needs.benchmark.result }} = success
