name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  benchmark:
    strategy:
      matrix:
        benchmark:
          - simple
          - nested
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: raviqqe/enable-homebrew@0cd19e7c245801a3494a29415862f79b874536aa # v1.0.4
      - run: brew install ninja
      - run: cargo install --path . --locked
      - run: benchmark/${{ matrix.benchmark }}/main.sh
  benchmark_test:
    runs-on: ubuntu-latest
    needs: benchmark
    if: always()
    steps:
      - run: test ${{ needs.benchmark.result }} = success
