name: bench
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  hyperfine:
    strategy:
      matrix:
        benchmark:
          - simple
          - nested
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - uses: raviqqe/enable-homebrew@6bd383659a321c332bd0c0ed445c32d54e04efe8 # v1.0.5
      - run: brew install ninja
      - run: cargo install --path . --locked
      - run: benchmark/${{ matrix.benchmark }}/main.sh
  bench:
    needs:
      - hyperfine
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
